import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
import BootstrapActivation from "@/components/BootstrapActionvation";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { UserState } from "@/state/UserState";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <UserState>

        <Header />
        {children}
        <Footer />
        <BootstrapActivation />
        </UserState>

      </body>
    </html>
  );
}
